# Generated by Django 2.2.3 on 2019-07-20 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('story_text', models.TextField()),
                ('publication_date', models.DateTimeField(default=datetime.datetime.now)),
                ('story_photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
